# Generated by Django 3.1.2 on 2020-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0003_auto_20201102_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
