# Generated by Django 3.1.2 on 2020-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0007_auto_20201103_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
